import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayoutWrapper from "./components/layout/ClientLayoutWrapper";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="es">
      <body className="min-h-screen flex flex-col md:flex-row">
        <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
        <Toaster richColors position="top-center" closeButton />
      </body>
    </html>
  );
}
