import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import Footer from "./components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="min-h-screen flex flex-col md:flex-row">
        {/* Sidebar fijo en pantallas grandes */}
        <div className="hidden md:block w-64 bg-blue-700 text-white">
          <Sidebar />
        </div>

        {/* Contenido principal */}
        <div className="flex-1 flex flex-col">
          {/* Sidebar móvil */}
          <div className="md:hidden p-2">
            <Sidebar />
          </div>
          <Header />
          <main className="flex-1 p-6 bg-gray-100">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
